#env: waggle
#workload: bitbrain
scheduler: WaggleScheduler
dataloader: SimpleLoader
steps: 10
# visualization: WanDB
visualization: TensorBoard
hosts:
- name: T001
  device: xaviernx
  labels:
    waggle.io/type: wsn
    waggle.io/group: chicago
- name: T002
  device: xaviernx
  labels:
    waggle.io/type: wsn
    waggle.io/group: nu
- name: T003
  device: xaviernx
  labels:
    waggle.io/type: wsn
    waggle.io/group: chicago
- name: T004
  device: xaviernx
  labels:
    waggle.io/type: wsn
    waggle.io/group: nu